# Generated by Django 4.2.3 on 2023-07-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=10)),
                ("city_id", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("locality", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("country_id", models.IntegerField()),
                ("locality_verbose", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votes", models.IntegerField()),
                ("rating_text", models.CharField(max_length=100)),
                ("rating_color", models.CharField(max_length=20)),
                ("aggregate_rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lat_long", models.CharField(max_length=100)),
                ("offers", models.CharField(max_length=255)),
                ("cuisine", models.CharField(max_length=10000)),
                ("currency", models.CharField(max_length=10)),
                ("price_range", models.CharField(max_length=20)),
                ("mezzo_provider", models.CharField(max_length=100)),
                ("order_deeplink", models.URLField()),
                ("book_form_web_view_url", models.URLField()),
                ("has_table_booking", models.BooleanField()),
                ("is_delivering_now", models.BooleanField()),
                ("opentable_support", models.BooleanField()),
                ("has_online_delivery", models.BooleanField()),
                ("include_bogo_offers", models.BooleanField()),
                ("switch_to_order_menu", models.BooleanField()),
                ("is_book_form_web_view", models.BooleanField()),
                ("is_table_reservation_supported", models.BooleanField()),
                ("average_cost_for_two", models.IntegerField()),
                (
                    "items",
                    models.ManyToManyField(related_name="restaurants", to="App.dish"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.location"
                    ),
                ),
                (
                    "user_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.userrating"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="App.restaurant"
            ),
        ),
    ]
