# Generated by Django 4.2.3 on 2023-07-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                ("city_id", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("country_id", models.FloatField(blank=True, null=True)),
                (
                    "locality_verbose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votes", models.FloatField(blank=True, null=True)),
                (
                    "rating_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rating_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("aggregate_rating", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("lat_long", models.CharField(max_length=100)),
                ("offers", models.CharField(blank=True, max_length=255, null=True)),
                ("cuisine", models.CharField(max_length=10000)),
                ("currency", models.CharField(max_length=10)),
                ("price_range", models.CharField(max_length=20)),
                (
                    "mezzo_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_deeplink", models.URLField(blank=True, null=True)),
                ("book_form_web_view_url", models.URLField(blank=True, null=True)),
                ("has_table_booking", models.BooleanField(blank=True, null=True)),
                ("is_delivering_now", models.BooleanField(blank=True, null=True)),
                ("opentable_support", models.BooleanField(blank=True, null=True)),
                ("has_online_delivery", models.BooleanField(blank=True, null=True)),
                ("include_bogo_offers", models.BooleanField(blank=True, null=True)),
                ("switch_to_order_menu", models.BooleanField(blank=True, null=True)),
                ("is_book_form_web_view", models.BooleanField(blank=True, null=True)),
                (
                    "is_table_reservation_supported",
                    models.BooleanField(blank=True, null=True),
                ),
                ("average_cost_for_two", models.FloatField(blank=True, null=True)),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="restaurants", to="App.dish"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App.location",
                    ),
                ),
                (
                    "user_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App.userrating",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="App.restaurant"
            ),
        ),
    ]
