# Generated by Django 4.2.3 on 2023-07-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="average_cost_for_two",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="book_form_web_view_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="items",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="restaurants", to="App.dish"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="App.location",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="mezzo_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="offers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="order_deeplink",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="user_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="App.userrating",
            ),
        ),
    ]
